/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class emu_Main */

#ifndef _Included_emu_Main
#define _Included_emu_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     emu_Main
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_emu_Main_print
  (JNIEnv *, jobject);

/*
 * Class:     emu_Main
 * Method:    initCpu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_emu_Main_initCpu
  (JNIEnv *, jobject, jint);

/*
 * Class:     emu_Main
 * Method:    runCpu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_emu_Main_runCpu
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
